[package]
name = "vix-syntax"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
vix-core = { path = "../core" }
tree-sitter.workspace = true
tree-sitter-highlight.workspace = true
tree-sitter-rust.workspace = true
tree-sitter-python.workspace = true
tree-sitter-javascript.workspace = true
tree-sitter-typescript.workspace = true
tree-sitter-go.workspace = true
tree-sitter-md.workspace = true
tree-sitter-json.workspace = true
tree-sitter-toml-ng.workspace = true
tree-sitter-html.workspace = true
tree-sitter-css.workspace = true
tree-sitter-bash.workspace = true
anyhow.workspace = true
